#! /bin/sh

case "$1" in
    start)
        chgrp gpio /sys/class/gpio/export
        chgrp gpio /sys/class/gpio/unexport
        chmod g+w /sys/class/gpio/export
        chmod g+w /sys/class/gpio/unexport
        ;;
    stop)
        chgrp root /sys/class/gpio/export
        chgrp root /sys/class/gpio/unexport
        chmod g-w /sys/class/gpio/export
        chmod g-w /sys/class/gpio/unexport
        ;;
    *)
        exit 1
        ;;
esac
